### ISSUE TITLE
Console flooding undefined variable messages.

### ISSUE THREAD

**Issue by daniktheboss** [Ad5001/BetterGen#11]
Hello, i keep getting console spam af when i create a world

**Comment by Ad5001** [comment]
Can you tell me what does it spam?

**Comment by inxomnyaa** [comment]
shit the spam is real.. 
![image](https://cloud.githubusercontent.com/assets/8733998/25935463/94bcf594-3623-11e7-95b4-993628672884.png)
![image](https://cloud.githubusercontent.com/assets/8733998/25935488/acbc5536-3623-11e7-9e7a-f7e9c163d545.png)
![image](https://cloud.githubusercontent.com/assets/8733998/25935515/c5a44496-3623-11e7-82f9-1ab907637d3d.png)
![image](https://cloud.githubusercontent.com/assets/8733998/25935705/a4e0e376-3624-11e7-90a2-6c301d49e747.png)

**Comment by Ad5001** [comment]
Ok are these the only errors? If so, it's fixed. Feel free to reopen this issue if it happends again ;)

**Comment by inxomnyaa** [comment]
i see no fixes for: mineshaft, cactus, the generator itself, caves. ^ check the 4 images

**Comment by Ad5001** [comment]
Oh ok I havent seen the other errors. Fixing them tomorrow.

**Comment by inxomnyaa** [comment]
Nope. I am fixing them on my fork and pr. Before you start adding more or forget things because your ide doesnt show you (eclipse i bet. shitty ide)

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/25942475/3d2ad124-363d-11e7-8cee-00bc0761ce40.png)
example

**Comment by Ad5001** [comment]
I use VSC. But I used Eclipse.

**Comment by Ad5001** [comment]
Fixed wih PR.
