### ISSUE TITLE
Are default biomes defined by the the software used in BetterGen?

### ISSUE THREAD

**Issue by DerddyDert** [Ad5001/BetterGen#13]
Does this simply modify certain biomes that you had specified with the biome php files and allow other biomes to still generate as usual? For example, GenisysPro has about 39 different biomes as seen here: https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/level/generator/biome/Biome.php
Would SAVANNA, EXTREME_HILLS_PLUS and MUSHROOM_ISLAND still generate? Thankyou for your time!

**Comment by inxomnyaa** [comment]
https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/level/generator/biome/Biome.php#L119-L138

Genisys("Pro") does not actually generate those either

**Comment by Ad5001** [comment]
No, it will not add biomes that are speicfied in your default sofware generator. Only Oceans Plains Taiga and swamps are used from the normal gen.
