### ISSUE TITLE
BetterGen does not generate under some circumstances

### ISSUE THREAD

**Issue by DerddyDert** [Ad5001/BetterGen#15]
After creating a world and entering it it generates fine. However, the world will stop generating using BetterGen when the world is defined to load when the server starts in the pocketmine.yml 

If you remove it from pockemine.yml then you enter the world during gameplay, of course in a different location, it will go back to generating using BetterGen. This is also the case if it is set as level-name=BetterGenWorld in the pocketmine.server 

BetterGen seems to have an issue being the generator if any map is loaded at server start rather than if a player actively goes there causing the world to load. Perhaps you can force it to load the plugin before the server loads the "level" and worlds: ?

**Comment by inxomnyaa** [comment]
you have to set the generator in that "worlds" option too, you know that right? Weird, but thats how pmmp works :(

**Comment by DerddyDert** [comment]
Yes for creating a new world thats true. Once you do it has the generator specified in the level.dat. But it still doesn't matter. If you load the level in pocketmine.server and you also have the level.dat info specifying the generator and you also specify level-type=betternormal it still will not generate using BetterGen.

**Comment by Ad5001** [comment]
I think it should be easily fixable using load: STARTUP.

**Comment by inxomnyaa** [comment]
@Ad5001 Correct, my thought. Tested and looks good. Othervise the generator doesn't exist on world preparation
