### ISSUE TITLE
Feature Request: Add the other features back

### ISSUE THREAD

**Issue by AvgZing** [Ad5001/BetterGen#17]
You should add the other features back, otherwise we will have no features left. If needed, add a config that sets __ to false by default, but the user can set it to true if they do not mind the bugs

**Comment by AvgZing** [comment]
Invalid issue, but its still a suggestion

**Comment by Thunder33345** [comment]
i think it's valid issues is used to suggest anyways...

**Comment by Ad5001** [comment]
Along with disabling features, you will be able to reenable some.

**Comment by Thunder33345** [comment]
i think just call these "experimental" features...

**Comment by AvgZing** [comment]
yeah
