### ISSUE TITLE
Feature Request: fallen trees

### ISSUE THREAD

**Issue by jasonw4331** [Ad5001/BetterGen#2]
In vanilla MCPE, fallen trees with mushrooms growing on them can be found in all the different forests.

**Comment by Ad5001** [comment]
That could ,be done. I will think about it...

**Comment by AvgZing** [comment]
Perhaps it could also include a variation on the fallen trees, where its not just 4 horizontal logs, but it also has some leaves on the ground around it. More realistic, I think

**Comment by Ad5001** [comment]
There are already bushes. Maybe but I don't know if it wouldn't be too much...

**Comment by AvgZing** [comment]
The more features the better!

**Comment by Ad5001** [comment]
Well, starting it then :)

**Comment by AvgZing** [comment]
:+1:

**Comment by Ad5001** [comment]
Just need a little more testing...

**Comment by Thunder33345** [comment]
idea population rates like with custom preset to make it customisable for example

**Comment by Ad5001** [comment]
@Thunder33345 Make an new issue for that ;). Plus give some more precisions because I'm not sure if I understanded

**Comment by Thunder33345** [comment]
by that i meant a customizability like when you go into custom worlds you can set ore rates sea level etc...

maybe a webapp to generate the present code to go with it but that's for future

**Comment by HimbeersaftLP** [comment]
> maybe a webapp to generate the present code to go with it but that's for future

Thought about that too xD
@Ad45001 I could make that web app when you have implemented the presets (and if you even do) lol

**Comment by Ad5001** [comment]
If I make this, I will not use presets. I will use options which will be easier for me and the user.
If you want, I'm making a wiki rn while coding. You will see infos about customizing the world.

**Comment by HimbeersaftLP** [comment]
> If I make this, I will not use presets. I will use options which will be easier for me and the user.

What do you mean with options? I hope it's not an extra config thingy...

**Comment by Ad5001** [comment]
Nonono. It's the thing presets is saved in ;) It's stored as an array.
If you use /createwold, you can use /createworld &lt;world name&gt; [generator = betternormal] [seed = rand()] [options(json)] ;)

**Comment by HimbeersaftLP** [comment]
Uhmm, then there isn't any difference to presets, isn't it?

**Comment by Ad5001** [comment]
There are differences. A preset is something like this:
;0;8*minecraft:grass;minecraft:village;

**Comment by Ad5001** [comment]
Ok after tears and research, I will use presets, but not in the way Minecraft deaulot gen is made. I will use preset to make save json data ;)

**Comment by HimbeersaftLP** [comment]
XD

**Comment by Ad5001** [comment]
Oops
