### ISSUE TITLE
Rewrite loot chest generation

### ISSUE THREAD

**Issue by inxomnyaa** [Ad5001/BetterGen#21]
relates to loottables #10 
Fix missing tiles -.-

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/26032424/d508b012-3893-11e7-9eee-2ac18e5bffc4.png)

**Comment by inxomnyaa** [comment]
Loot chest generation fixed, functions cleaned up AF

**Comment by DerddyDert** [comment]
Will this actually spawn chests in temples and whatnot?

**Comment by inxomnyaa** [comment]
it does.
