### ISSUE TITLE
Crashes when trying to login

### ISSUE THREAD

**Issue by DerddyDert** [Ad5001/BetterGen#23]
I started a new test server, installed from your most recent source, created a world. I set that world to the "level" in server.properties and when I log on it gets stuck trying to load world and console says:
`[06:55:28] [Asynchronous Worker #1 thread/CRITICAL]: Error: "Call to undefined m              ethod Ad5001\BetterGen\populator\MineshaftPopulator::getHighestBlockAt()" (EXCEP              TION) in "/BetterGen-master/src/Ad5001/BetterGen/populator/MineshaftPopulator" a              t line 90
[06:55:28] [Server thread/CRITICAL]: Could not execute asynchronous task Populat              ionTask: Task crashed
`

**Comment by jasonw4331** [comment]
wasn't that supposed to be the getHighestWorkableBlock function?

**Comment by Ad5001** [comment]
Yes oops.
