### ISSUE TITLE
Can you add sea in generator?

### ISSUE THREAD

**Issue by Saxavlax001** [Ad5001/BetterGen#25]

**Comment by Ad5001** [comment]
What do you mean?

**Comment by Saxavlax001** [comment]
I mean mcpe has ocean biome

**Comment by AvgZing** [comment]
Like ocean monuments and islands in the sea?

**Comment by Saxavlax001** [comment]
![screenshot_2017-05-19-00-38-43](https://cloud.githubusercontent.com/assets/22281205/26224605/c196ef8a-3c2b-11e7-90c1-0093456a71b7.png)

Yes something like the picture a bit and that you said,islands etc.,if there are possible to add.

**Comment by Ad5001** [comment]
You can use the new beta options system (soon documented): {"deleteBiomes":"Plains,BetterDesert,OakForest,BirchForest,SakuraForest,BetterIcePlains,BetterMesa,BetterMesaPlains,BetterRiver"}

You would use it like: /createworld &lt;world name> betternormal &lt;seed> &lt;options>
