### ISSUE TITLE
Undefined property trunk height - console spamming

### ISSUE THREAD

**Issue by kabluinc** [Ad5001/BetterGen#29]
The console is spamming with the error below.

`Notice: Undefined property: pocketmine\level\generator\object\OakTree::$trunkHeight in C:\Users\Administrator\Desktop\New fold\plugins\BetterGen-master\src\Ad5001\BetterGen\structure\FallenTree.php on line 72
Vector3(x=188,y=65,z=160) is not overwritable (106).
`

**Comment by Ad5001** [comment]
Try the 1.0 phar. This branch is unstable

**Comment by Ad5001** [comment]
This bug has been fixed in the latest commit.
