### ISSUE TITLE
Update Plugin.yml

### ISSUE THREAD

**Issue by daniel022302** [Ad5001/BetterGen#30]
Update to 3.0.0 and 3.0.0-ALPHA5 please

**Comment by Ad5001** [comment]
The plugin in master is higly unstable. I recommend you downloading the Release one.

**Comment by daniel022302** [comment]
But it's not working with 1.1

**Comment by Ad5001** [comment]
Updated to latest API (3.0.0-ALPHA6)

**Comment by Dub-Boy** [comment]
I don't see the update for 3.0.0-ALPHA6, anywhere the plugin with this api version can be found? Or should I just bump the api myself?

**Comment by inxomnyaa** [comment]
it was recent
https://github.com/pmmp/PocketMine-MP/commit/19410754c682fe9c50da99223ef1bca0c524673e
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/PocketMine.php#L82

**Comment by Dub-Boy** [comment]
@thebigsmileXD I was referring to the plugin fyi, dev said plugin was updated but I don't see the update pushed. So I was just wondering.

**Comment by inxomnyaa** [comment]
Confirming. https://github.com/Ad5001/BetterGen/blob/loottables/plugin.yml#L17

**Comment by AvgZing** [comment]
@thebigsmileXD maybe you could actually fix the issue yourself instead of just opening the issue? Thanks

**Comment by Ad5001** [comment]
The github release is updated. The master branch is higly unstable.

**Comment by inxomnyaa** [comment]
@theroyalblock maybe you should do it because you seem like someone who can argue about knowledge?

**Comment by AvgZing** [comment]
I am the kind of person who loves to argue, but I do not have repo access, therefore I cannot do it myself.

**Comment by jasonw4331** [comment]
@TheRoyalBlock there is a thing called a Pull Request on git for edits to be made without repo access. Use it if you think you can fix the issue.

**Comment by inxomnyaa** [comment]
∆ exactly what he said.
