### ISSUE TITLE
Alpha-7 Incompatible

### ISSUE THREAD

**Issue by gitgarage** [Ad5001/BetterGen#32]
But I was able to fork your code and fix that. Please merge my code into yours if you get a chance.

https://github.com/GitGarage/BetterGen

**Comment by Ad5001** [comment]
I know I need to fix it. But nowadays, I don't have much time, unfortunatly.

**Comment by gitgarage** [comment]
Its ok, its working for me at least. Rad plug in, by the way. Much better than the default level generator. I love the temples and igloos.

**Comment by inxomnyaa** [comment]
-8 is out

**Comment by gitgarage** [comment]
You are right. Nice catch. I bumped BetterGen's plugin.yml file to include Alpha-8 just now, and it still appears to work, still testing though. https://github.com/GitGarage/BetterGen/releases/download/1.1/BetterGen_v1.1_ALPHA_7_8.phar

**Comment by GitGarage** [comment]
Nevermind no need for DevTools, I was able to compile a BetterGen phar file which can just be added to the plugins folder.

**Comment by Ad5001** [comment]
This bug has been fixed in the latest commit.
