### ISSUE TITLE
Not Working for 1.2 (3.0.0-ALPHA9)

### ISSUE THREAD

**Issue by ghost** [Ad5001/BetterGen#33]
Please fix this, i love this plugin

**Comment by Ad5001** [comment]
I know. I will fix it when i'll have the time (in ~1 or 2 weeks)

**Comment by gitgarage** [comment]
I tried just bumping the api to include 3.0.0-ALPHA9. My own server is still running on the old version, could you give it a try @BlawoHD?

https://github.com/GitGarage/BetterGen/releases

**Comment by Ad5001** [comment]
@GitGarage Bumping the API alone wouldn't work. There's a lot of breaking changes in the latest apis.

**Comment by AvgZing** [comment]
Unfortunately... This destroys compatibility with spoons *sigh*

**Comment by gitgarage** [comment]
I changed it a bunch to get it to work with ALPHA-7, and a simple bump made it work with ALPHA-8. This bump I did today may work, although it sounds like it breaks spoons.

**Comment by AvgZing** [comment]
will not work on pm

**Comment by HimbeersaftLP** [comment]
> Unfortunately... This destroys compatibility with spoons sigh

There is no active spoon for MCPE 1.2 that still uses the old API afaik

(Steadfast does not count as spoon)

**Comment by AvgZing** [comment]
Then what does Steadfast count as?

**Comment by HimbeersaftLP** [comment]
Knife? Idk, but they aren't a spoon by my measurings.

Spoon: Not a fork, directly uploaded from a .zip (no previous commit history), """devs""" don't know what they're doing and can only copy and paste

**Comment by wyt3dr4g0n** [comment]
I agree on Steadfast... lol. I have a modified version of this that seems to work with Alpha 9. Wasn't much to have to fix, just some block names, return types for compatibility, and various other bits. I successfully generated a world and can TP to it. Looks gorgeous!!

**Comment by Ad5001** [comment]
This bug has been fixed in the latest commit.
