### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by ghost** [Ad5001/BetterGen#38]
```[18:21:51] [Server thread/CRITICAL]: Could not save Config C:\Users\mikha\Desktop\PocketMine-MP\BetterGen\processingLoots.json: file_put_contents(C:\Users\mikha\Desktop\PocketMine-MP\BetterGen\processingLoots.json): failed to open stream: No such file or directory```

**Comment by Ad5001** [comment]
Create a directory called "BetterGen" in your source server folder.
