### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by daniktheboss** [Ad5001/BetterGen#4]
i cant get the gen to work. It is same as normal pocketmine gen

**Comment by Ad5001** [comment]
What did you do to generate the world?

**Comment by Ad5001** [comment]
Hmm... Do you see any error in the console?

**Comment by daniktheboss** [comment]
it said ore.php not found... other then that no

**Comment by Ad5001** [comment]
Ok. I've seen on Twitter that you were using Tesseract, which, unfortunatly, has decided to have different namespaces. I'd need to do a check for every single file to chek which soft is this using so which folder structure.

**Comment by daniktheboss** [comment]
o ok

**Comment by Ad5001** [comment]
Ok. I just finished debugging it with the latest version of Tesseract :). Redownload it and it should now work :)
