### ISSUE TITLE
Water and lava not falling after generation

### ISSUE THREAD

**Issue by ghost** [Ad5001/BetterGen#42]
Should water and lava spill?
![Screenshot](https://i.imgur.com/WPpuwIH.png)

**Comment by AvgZing** [comment]
Yes. This is a server-side problem, not plugin. When water and lava spawn by default, they do not move.They will not spill until a block is placed then broken next to the water or lava

**Comment by Ad5001** [comment]
Well, this is an issue with PocketMine-MP not having implemented randomtickspeed :) RandomTickSpeed basicly updates randomly blocks around the player and so, the water and lava would flow (just place a block next to it and it should update.
