### ISSUE TITLE
how i can use this?

### ISSUE THREAD

**Issue by RubyTemple** [Ad5001/BetterGen#49]
how i can generate a custom world type pictures?

**Comment by Ad5001** [comment]
/createworld <name> [generator = betternormal] [seed = rand()] [options(json)]

**Comment by RubyTemple** [comment]
Yes but create a normal world...

**Comment by Ad5001** [comment]
Do you mean that the generated world is the same as a normal one? Are you sure you're using an official bettergen version?

**Comment by MonoAdrian23** [comment]
Funktioniert nicht!

**Comment by MonoAdrian23** [comment]
Egal von wo man den Befehl eingibt, es passiert nix. Finde ich wirklich sehr schade da es Mal eine Alternative wäre zu dieser langweiligen Pocketmine Fw.
