### ISSUE TITLE
Options to disable features

### ISSUE THREAD

**Issue by inxomnyaa** [Ad5001/BetterGen#8]
I'd like not to have these Bushes or floating islands or wool trees, can you add options to this?

**Comment by Ad5001** [comment]
This is a great idea. Thought settings will be for the whole server.

**Comment by Thunder33345** [comment]
is it possible for perworld settings?
like how presets works?

**Comment by HimbeersaftLP** [comment]
> is it possible for perworld settings?
like how presets works?

Yeah, that would be cool to make it like the flatworld settings

**Comment by Ad5001** [comment]
Yeah maybe... I will look into this.

**Comment by Ad5001** [comment]
Finished !

**Comment by AvgZing** [comment]
Yay!
