### ISSUE TITLE
Fix height

### ISSUE THREAD

**Issue by inxomnyaa** [Ad5001/BetterGen#9]
https://github.com/Ad5001/BetterGen/blob/master/src/Ad5001/BetterGen/populator/LakePopulator.php#L54
I saw it on several things. Level.php has a height value which could be used instead

**Comment by Ad5001** [comment]
Please note that every structures are executed async and the blocks are set in a SimpleChunkManager which has almost no method except setting blocks.

**Comment by inxomnyaa** [comment]
.. you can still access LEVEL::xxx constants..
